### ISSUE TITLE
In production create-react-app causes DOMException: Failed to execute 'postMessage' on 'Worker': function(e) error, but not development

### ISSUE THREAD

**Issue by batmilkyway** [alexmojaki/comsync#6]
I'm working on an app that mimics the same approach [papyros](https://github.com/dodona-edu/papyros) uses for multiple backends for browser code execution. Curiously, with python and pyodide, everything works fine when running in development, but when doing a production build the following error happens when doing `backend.call(backend.workerProxy.runCode, ...)`

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': function(e){var t;o&&"init"!==e&&("reading"===e?(l.state="awaitingMessage",l._messageIdSeq++,null===(t=l._await...<omitted>...)} could not be cloned.
    at http://localhost:3000/static/js/main.bd11f364.js:2:212380
    at new Promise (<anonymous>)
    at C (http://localhost:3000/static/js/main.bd11f364.js:2:212080)
    at Object.apply (http://localhost:3000/static/js/main.bd11f364.js:2:210833)
    at n.<anonymous> (http://localhost:3000/static/js/main.bd11f364.js:2:3973)
    at d (http://localhost:3000/static/js/main.bd11f364.js:2:196064)
    at Generator.<anonymous> (http://localhost:3000/static/js/main.bd11f364.js:2:197401)
    at Generator.next (http://localhost:3000/static/js/main.bd11f364.js:2:196427)
    at http://localhost:3000/static/js/main.bd11f364.js:2:2166
```
which seems to be because Babel is transpiling whatever is being sent via `postMessage` into a function when doing a production build, but not in development. Specifically it seems to be the `syncMessageCallback` that is causing the issue, even though it's wrapped in a `proxy`.

**Comment by alexmojaki** [comment]
Relevant: https://github.com/GoogleChromeLabs/comlink/issues/579

I ran into this problem when the `target` in `tsconfig.json` was `es5` instead of `es6`. That made this code:

```ts
        proxyMethod(
          this.channel,
          Comlink.proxy(syncMessageCallback),
          this._messageIdBase,
          ...args,
        ),
```

transpile into something using `.apply` instead of keeping the `...` spread syntax, which messes with comlink's ability to detect the proxy.

**Comment by batmilkyway** [comment]
Hmm, I just tried with my tsconfig target set to es6 and it's still happening. It seems like I need to fork comlink the and fix the issue myself based on https://github.com/GoogleChromeLabs/comlink/issues/579#issuecomment-1060122519 or is there anything I can do in my code? I'm very new to frontend development, so maybe there's an obvious solution I'm missing.

edit: I tried forking with the change from that comment and it still didn't work :sob:

**Comment by alexmojaki** [comment]
Sorry, I also have a pretty poor understanding of bundling and stuff. In futurecoder, which is also a create-react-app, I don't use typescript, which might be the only reason I haven't also faced this there.

On the bundling side, try to create a minimal reproducible example that you can ask about on StackOverflow. See how many parts of the setup you can remove before the problem disappears, e.g:

1. Replace comsync with a call to comlink using `...`
2. Remove comlink and just call some random code with `...` and see if `...` is in the production bundle.
3. Remove typescript.

Otherwise, to fix this in comlink, I think the code path to look at is `apply -> processArguments -> toWireValue`. Currently it only sees proxies at the top level, it needs to be able to see them inside arrays too.

I'd love a solution that doesn't require forking comlink or knowing much about bundling, but I don't know how. If comsync just passed `args` instead of `...args`, then `Comlink.proxy(syncMessageCallback)` would probably be handled fine but `args` itself is typically expected to also contain one or more proxies which brings us back to square one.

**Comment by batmilkyway** [comment]
Thanks for the detailed reply, I'll be giving these a shot. I'll close this issue then as it sounds like the issue is wholly with comlink and there's no reasonable workaround within comsync.

**Comment by batmilkyway** [comment]
In the end I decided the easiest thing to do was fork comlink myself along with comsync and sync-message to point to the forked comlink. On the plus side, everything works as expected, even if the resolution is extremely hacky, the result is here https://glittering-narwhal-96bc3e.netlify.app/
